# Generated by Django 4.2.4 on 2023-08-24 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='changing_data',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
