# Generated by Django 4.2.4 on 2023-08-24 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_client_changing_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log',
            options={'verbose_name': 'Лог', 'verbose_name_plural': 'Логи'},
        ),
    ]
