# Generated by Django 4.2.4 on 2023-08-25 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_alter_log_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailing',
            name='recipients',
        ),
        migrations.AddField(
            model_name='mailing',
            name='recipients',
            field=models.ManyToManyField(blank=True, null=True, to='mailing.client', verbose_name='Получатели'),
        ),
    ]
